name: "Demo.Containers"
concurrency: "Demo.Containers"
env: 
  APP_NAME: cherademoproductsapi
  RG_NAME: rg-chera-demo
  RG_LOCATION: australiasoutheast
  DOTNET_VERSION: 6.0.x
  PUBLISHED_PATH: ./published

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    
jobs: 
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      BUILD_VERSION: $(date +%Y%m%d_%H%M%S)
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Restore projects
        run: dotnet restore
      - name: Build Projects      
        run: dotnet build --no-restore -c Release                
          
      - name: Login to Docker
        run: |
          docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build Docker Image
        run: |
          docker build -t ${{secrets.DOCKER_USER}}/demoproductsapi:${{env.BUILD_VERSION}} --file Demo.Containers.Products.Api/Dockerfile .
      - name: Push to Docker
        run: |
          docker push ${{secrets.DOCKER_USER}}/demoproductsapi:${{env.BUILD_VERSION}}
            
           
            