name: "Demo.Containers"
concurrency: "Demo.Containers"
env: 
  APP_NAME: cherademoproductsapi
  RG_NAME: rg-chera-demo
  RG_LOCATION: Australia Southeast
  DOTNET_VERSION: 6.0.x
  PUBLISHED_PATH: ./published
  

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    
jobs: 
  build:
    name: Build and Deploy
    runs-on: windows-latest    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Restore projects
        run: dotnet restore
      
      - name: Build Projects
        run: dotnet build --no-restore -c Release
      
      - name: Publish
        run: dotnet publish -c Release --no-build -o ${{ env.PUBLISHED_PATH }}/api
        
      - name: Publish Artifact - API
        uses: actions/upload-artifact@v1.0.0
        with:
          name: api
          path: ${{ env.PUBLISHED_PATH }}
          
  deploy-staging:
    needs: build
    runs-on: windows-latest
    
    environment: 
      name: PRE-PROD
      
    steps:
      - name: Login to Azure CLI
        uses: azure/login@v1
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Create Resource Group ${{ env.RG_NAME }}
        uses: azure/CLI@v1
        with:
          inlineScript: |
            #!/bin/bash            
            if $(az group exists --name ${{ env.RG_NAME }}) ; then
              echo "Azure resource group already exists, skipping creation..."
            else
              az group create --name ${{ env.RG_NAME }} --location ${{ env.RG_LOCATION }}
              echo "Azure resource group created"
            fi

